# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Flowers',
        ),
    ]
