# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190912_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flower',
            name='author',
        ),
        migrations.RemoveField(
            model_name='flower',
            name='text',
        ),
        migrations.AddField(
            model_name='flower',
            name='price',
            field=models.CharField(default=0, max_length=16),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flower',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
