# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190912_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='categories',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
