# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-09-12 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_flower_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('categories', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=16)),
            ],
        ),
    ]
